/**
 * Reads the vault graph the daily build script writes.
 *
 * Live copy lives at ~/.sam/vault-graph.json, regenerated by the
 * sam-vault-graph systemd timer. If it is missing or unreadable — fresh clone,
 * dev machine, timer never enabled, unit failed — we fall back to the snapshot
 * committed at src/data/vault-graph.json so the intro always has something to
 * draw. A boot screen that renders nothing because a cron job failed is a worse
 * failure than a boot screen showing a slightly stale graph.
 */

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import snapshotJson from '@/data/vault-graph.json';
import type { VaultGraph } from '@/types/vaultGraph';

// TypeScript infers imported JSON arrays as `number[][]` and `ring` as `number`,
// neither of which satisfies the tuple and union types in VaultGraph. The file
// is generated by the same script that writes the live copy, so the shape is
// guaranteed by construction rather than by the compiler here.
const snapshot = snapshotJson as unknown as VaultGraph;

const LIVE_PATH = path.join(os.homedir(), '.sam', 'vault-graph.json');
const CACHE_MS = 60_000;

export type VaultGraphSource = 'live' | 'snapshot';

export interface VaultGraphResult {
  graph: VaultGraph;
  source: VaultGraphSource;
}

let cached: { at: number; result: VaultGraphResult } | null = null;

/** Cheap shape check — a truncated or half-written file must not reach the client. */
function isValid(value: unknown): value is VaultGraph {
  if (typeof value !== 'object' || value === null) return false;
  const g = value as Partial<VaultGraph>;
  return (
    Array.isArray(g.nodes) &&
    Array.isArray(g.edges) &&
    g.nodes.length > 0 &&
    typeof g.hub === 'number' &&
    typeof g.generatedAt === 'number'
  );
}

function readLive(): VaultGraph | null {
  try {
    const raw = fs.readFileSync(LIVE_PATH, 'utf-8');
    const parsed: unknown = JSON.parse(raw);
    return isValid(parsed) ? parsed : null;
  } catch {
    // Missing file, bad JSON, no permission — all mean "use the snapshot".
    return null;
  }
}

export function getVaultGraph(): VaultGraphResult {
  const now = Date.now();
  if (cached && now - cached.at < CACHE_MS) return cached.result;

  const live = readLive();
  const result: VaultGraphResult = live
    ? { graph: live, source: 'live' }
    : { graph: snapshot, source: 'snapshot' };

  cached = { at: now, result };
  return result;
}
