#!/usr/bin/env python3
"""Print the n8n recipient allowlist, derived from the vault.

The n8n webhook re-validates every recipient against a hardcoded list. That
duplication is deliberate: the list's whole value is being *independent* of
SAM_ui. If n8n asked SAM_ui "is this allowed?", a confused or compromised
SAM_ui would simply answer yes, and the second gate would become a rubber
stamp. So it stays a static list — this script just removes the tedium of
keeping it honest.

n8n cannot derive it itself either: only `02 - Atwood Systems` is mounted into
the container, so it cannot see contacts under `03 - Personal`.

Usage:
    ./omni_allowlist.py          # paste the output into the Validate node
"""

from __future__ import annotations

import os
import re
import sys

VAULT = os.environ.get("SAM_VAULT_PATH", "/home/col/ai-memory-vault")
IGNORED = {".obsidian", ".git", ".trash", "node_modules"}


def contacts(vault: str) -> list[tuple[str, str]]:
    found: list[tuple[str, str]] = []
    for root, dirs, files in os.walk(vault):
        dirs[:] = [d for d in dirs if d not in IGNORED and not d.startswith(".")]
        for name in files:
            if not name.endswith(".md"):
                continue
            path = os.path.join(root, name)
            try:
                with open(path, encoding="utf-8", errors="replace") as fh:
                    head = fh.read(2048)
            except OSError:
                continue
            if not head.startswith("---"):
                continue
            end = head.find("\n---", 3)
            if end == -1:
                continue
            fm = head[3:end]
            email = re.search(r"^email:\s*(\S+)", fm, re.M)
            status = re.search(r"^status:\s*(\S+)", fm, re.M)
            if not email or (status and status.group(1) == "archived"):
                continue
            found.append((name[:-3], email.group(1)))
    return sorted(found, key=lambda c: c[0].lower())


def main() -> int:
    people = contacts(VAULT)
    if not people:
        print(f"no contacts with an email: field under {VAULT}", file=sys.stderr)
        return 1

    print("// Generated by scripts/omni_allowlist.py — keep in step with the vault.")
    print("const ALLOWED = [")
    for name, email in people:
        print(f"  '{email.lower()}',".ljust(42) + f"// {name}")
    print("];")
    print(f"\n// {len(people)} recipients", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
