/**
 * SAM — a stand-in for the `claude` CLI binary, for tests.
 *
 * Real turns cost quota and are slow, and title calls hit a live Haiku
 * route (see the tickets file's "Haiku route for titles" note). Tests that
 * need a `claude` process instead point `SAM_CLAUDE_BIN` at the script this
 * writes; `claudeBin()` (src/lib/server/claudeBin.ts) already honours that
 * override, so nothing under test needs to know it is talking to a fake.
 *
 * The written script is a plain, dependency-free Node CLI (CommonJS, no
 * `@/` imports) so it runs standalone once written to disk — it is spawned
 * as a child process by whatever is under test, not `require`d by the test
 * itself.
 */

import fs from 'node:fs';
import path from 'node:path';

/**
 * Write an executable fake `claude` to `dir` and return its path.
 *
 * Behaviour (driven by argv and a handful of env vars the test sets):
 *  - parses `-p <prompt>`, `--session-id <id>`, `--resume <id>`, `--model <m>`;
 *  - appends one JSON line to `$FAKE_CLAUDE_LOG`, if set, holding argv, cwd,
 *    `CLAUDE_CONFIG_DIR` and `SAM_CHAT_ID`;
 *  - title mode (a `--model` value containing "haiku"): prints one JSON
 *    result line, or exits 1 when `FAKE_TITLE_FAIL=1`;
 *  - otherwise acts as a turn: sleeps `$FAKE_CLAUDE_DELAY_MS` (default 0),
 *    appends a user + assistant entry to the transcript file a real CLI
 *    would write, then — if `$FAKE_CLAUDE_POST_WRITE_DELAY_MS` is set —
 *    sleeps again before printing anything, holding the job "running" with
 *    the transcript entries already on disk (review finding 7's reattach
 *    window: a real CLI writes the user entry well before any reply exists,
 *    which this second delay lets a test catch), then prints system/init,
 *    assistant and result stream-json lines, and exits 0;
 *  - when the prompt contains a line "Write the memo to: <path>", also
 *    writes a short Markdown memo to that path, unless `FAKE_SKIP_MEMO=1`
 *    (a memo turn that ran but wrote nothing, as when a seat is at its
 *    limit — T18's missing-memo case).
 */
export function writeFakeClaude(dir: string): string {
  fs.mkdirSync(dir, { recursive: true });
  const scriptPath = path.join(dir, 'fake-claude.cjs');
  fs.writeFileSync(scriptPath, FAKE_CLAUDE_SOURCE, { mode: 0o755 });
  return scriptPath;
}

const FAKE_CLAUDE_SOURCE = `#!/usr/bin/env node
'use strict';

/* Generated by src/lib/server/testing/fakeClaude.ts — do not edit by hand. */

const fs = require('fs');
const path = require('path');
const os = require('os');
const crypto = require('crypto');

function parseArgs(argv) {
  const out = { prompt: '', sessionId: null, resume: null, model: null };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '-p') {
      out.prompt = argv[i + 1] || '';
      i++;
    } else if (a === '--session-id') {
      out.sessionId = argv[i + 1] || null;
      i++;
    } else if (a === '--resume') {
      out.resume = argv[i + 1] || null;
      i++;
    } else if (a === '--model') {
      out.model = argv[i + 1] || null;
      i++;
    }
  }
  return out;
}

/* Every character that is not a letter or digit becomes "-". Matches the
   app's own cwdSlug rule (agentCwd()'s cwd, replaced the same way). The fake
   uses its own process cwd rather than the caller's agentCwd(). */
function cwdSlug(dir) {
  return dir.replace(/[^A-Za-z0-9]/g, '-');
}

async function main() {
  const argv = process.argv.slice(2);
  const parsed = parseArgs(argv);

  if (process.env.FAKE_CLAUDE_LOG) {
    const entry = {
      argv: argv,
      cwd: process.cwd(),
      CLAUDE_CONFIG_DIR: process.env.CLAUDE_CONFIG_DIR || null,
      SAM_CHAT_ID: process.env.SAM_CHAT_ID || null,
    };
    fs.appendFileSync(process.env.FAKE_CLAUDE_LOG, JSON.stringify(entry) + '\\n');
  }

  const isTitleMode = typeof parsed.model === 'string' && parsed.model.indexOf('haiku') !== -1;

  if (isTitleMode) {
    if (process.env.FAKE_TITLE_FAIL === '1') {
      process.exitCode = 1;
      return;
    }
    const title = process.env.FAKE_TITLE || 'Fake Title';
    process.stdout.write(JSON.stringify({ type: 'result', is_error: false, result: title }) + '\\n');
    process.exitCode = 0;
    return;
  }

  const delayMs = Number(process.env.FAKE_CLAUDE_DELAY_MS || '0');
  if (delayMs > 0) {
    await new Promise((resolve) => setTimeout(resolve, delayMs));
  }

  const id = parsed.resume || parsed.sessionId || crypto.randomUUID();
  const configDir = process.env.CLAUDE_CONFIG_DIR || path.join(os.homedir(), '.claude');
  const slug = cwdSlug(process.cwd());
  const projectDir = path.join(configDir, 'projects', slug);
  fs.mkdirSync(projectDir, { recursive: true });
  const transcriptPath = path.join(projectDir, id + '.jsonl');

  const reply = process.env.FAKE_CLAUDE_REPLY || ('echo: ' + parsed.prompt);
  const now = new Date().toISOString();

  const userEntry = {
    type: 'user',
    message: { role: 'user', content: parsed.prompt },
    sessionId: id,
    cwd: process.cwd(),
    timestamp: now,
    uuid: crypto.randomUUID(),
  };
  const assistantEntry = {
    type: 'assistant',
    message: {
      role: 'assistant',
      content: [{ type: 'text', text: reply }],
    },
    sessionId: id,
    cwd: process.cwd(),
    timestamp: now,
    uuid: crypto.randomUUID(),
  };

  fs.appendFileSync(transcriptPath, JSON.stringify(userEntry) + '\\n');
  fs.appendFileSync(transcriptPath, JSON.stringify(assistantEntry) + '\\n');

  const postWriteDelayMs = Number(process.env.FAKE_CLAUDE_POST_WRITE_DELAY_MS || '0');
  if (postWriteDelayMs > 0) {
    await new Promise((resolve) => setTimeout(resolve, postWriteDelayMs));
  }

  const memoMatch = /^Write the memo to: (.+)$/m.exec(parsed.prompt);
  if (memoMatch && process.env.FAKE_SKIP_MEMO !== '1') {
    const memoPath = memoMatch[1].trim();
    fs.mkdirSync(path.dirname(memoPath), { recursive: true });
    fs.writeFileSync(memoPath, '# Memo\\n\\n' + reply + '\\n');
  }

  process.stdout.write(
    JSON.stringify({ type: 'system', subtype: 'init', session_id: id, model: parsed.model || 'fake-model' }) + '\\n',
  );
  process.stdout.write(
    JSON.stringify({ type: 'assistant', session_id: id, message: { content: [{ type: 'text', text: reply }] } }) +
      '\\n',
  );
  process.stdout.write(
    JSON.stringify({
      type: 'result',
      is_error: false,
      result: reply,
      session_id: id,
      total_cost_usd: 0,
      duration_ms: delayMs,
    }) + '\\n',
  );

  process.exitCode = 0;
}

main().catch((err) => {
  process.stderr.write(String((err && err.stack) || err) + '\\n');
  process.exitCode = 1;
});
`;
